import { StyleSheet } from "react-native";

export const COLORS = {
  orange: "#FF8200",
  background: "#FF7F7F7",
  text: "#1A1A1A",
  muted: "#666666",
  border: "#E2E2E2",
  placeholder: "#9A9A9A",
  error: "#C62828",
  white: "#FFFFFF",
};

export const authStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: COLORS.background },
  container: {
    flex: 1,
    justifyContent: "center",
    padding: 24,
    width: "100%",
    maxWidth: 440,
    alignSelf: "center",
  },
  title: { fontSize: 30, fontWeight: "800", color: COLORS.orange },
  subtitle: { fontSize: 16, color: COLORS.muted, marginTop: 4, marginBottom: 28 },
  card: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 24,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  cardHeading: { fontSize: 22, fontWeight: "700", color: COLORS.text, marginBottom: 16 },
  label: {
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
    color: COLORS.muted,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    color: COLORS.text,
    backgroundColor: COLORS.background,
    marginBottom: 16,
  },
  error: { color: COLORS.error, fontSize: 14, marginBottom: 12 },
  button: {
    backgroundColor: COLORS.orange,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 4,
  },
  buttonPressed: { opacity: 0.8 },
  buttonText: { color: COLORS.white, fontSize: 16, fontWeight: "700" },
  footer: { flexDirection: "row", justifyContent: "center", marginTop: 20 },
  footerText: { color: COLORS.muted, fontSize: 15 },
  link: { color: COLORS.orange, fontSize: 15, fontWeight: "700" },
});